### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/scikit-validate#20]
Restrict to Python >= 3.5

**Comment by hugovk** [comment]
See also [NEP 29 — Recommend Python and Numpy version support as a community policy standard](https://numpy.org/neps/nep-0029-deprecation_policy.html):

> This NEP recommends that all projects across the Scientific Python ecosystem adopt a common “time window-based” policy for support of Python and NumPy versions. Standardizing a recommendation for project support of minimum Python and NumPy versions will improve downstream project planning.
>
> This is an unusual NEP in that it offers recommendations for community-wide policy and not for changes to NumPy itself. Since a common place for SPEEPs (Scientific Python Ecosystem Enhancement Proposals) does not exist and given NumPy’s central role in the ecosystem, a NEP provides a visible place to document the proposed policy.
> 
> This NEP is being put forward by maintainers of Matplotlib, scikit-learn, IPython, Jupyter, yt, SciPy, NumPy, and scikit-image.


And so they suggest:

> On next release, drop support for Python 3.5 (initially released on Sep 13, 2015)

Looks like it will be accepted:
* https://www.mail-archive.com/numpy-discussion@python.org/msg03520.html
* https://www.mail-archive.com/numpy-discussion@python.org/msg03521.html

**Comment by kreczko** [comment]
@hugovk Thank you for the information, I was unaware of NEP 29.
For 0.4.0 (this year) we will support require Python 3.6+, numpy 1.14+ and for 0.5.0 (early next year) we will require Python 3.7+ and numpy 1.15+:

```
On next release, drop support for Python 3.5 (initially released on Sep 13, 2015)
On Jan 07, 2020 drop support for Numpy 1.14 (initially released on Jan 06, 2018)
On Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016)
On Jul 23, 2020 drop support for Numpy 1.15 (initially released on Jul 23, 2018)
On Jan 13, 2021 drop support for Numpy 1.16 (initially released on Jan 13, 2019)
On Jul 26, 2021 drop support for Numpy 1.17 (initially released on Jul 26, 2019)
On Dec 26, 2021 drop support for Python 3.7 (initially released on Jun 27, 2018)
```

@benkrikler Similarly for other projects?
